import jsPDF from "jspdf";

/**
 * Export a test/quiz as a printable PDF.
 * @param {object} opts
 * @param {string} opts.title - Test title
 * @param {string} opts.deckTitle - Deck/subject name
 * @param {Array}  opts.questions - Array of question objects
 * @param {boolean} opts.includeAnswerKey - Whether to append an answer key page
 */
export function exportTestPdf({ title, deckTitle, questions, includeAnswerKey = false }) {
  const doc = new jsPDF({ unit: "pt", format: "letter" });
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const margin = 50;
  const contentW = W - margin * 2;
  let y = margin;

  const COLORS = {
    primary: [109, 40, 217],   // violet-700
    dark: [15, 15, 20],
    muted: [120, 120, 130],
    line: [220, 220, 230],
    bubble: [245, 245, 250],
  };

  function ensureSpace(needed) {
    if (y + needed > H - margin - 40) {
      doc.addPage();
      y = margin;
    }
  }

  function drawHeader(pageTitle) {
    // Purple header bar
    doc.setFillColor(...COLORS.primary);
    doc.rect(0, 0, W, 36, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(255, 255, 255);
    doc.text("Cognita", margin, 23);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(pageTitle, W - margin, 23, { align: "right" });
    y = 56;
  }

  function drawFooter(pageNum, totalPages) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...COLORS.muted);
    doc.text(`Page ${pageNum} of ${totalPages}`, W / 2, H - 20, { align: "center" });
    doc.text("Generated by Cognita · cognita.app", margin, H - 20);
  }

  function wrapText(text, maxWidth, fontSize) {
    doc.setFontSize(fontSize);
    return doc.splitTextToSize(String(text || ""), maxWidth);
  }

  // ─── Page 1: Cover ──────────────────────────────────────────────────────────
  drawHeader("Practice Test");
  y = 100;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(26);
  doc.setTextColor(...COLORS.dark);
  const titleLines = wrapText(title || "Practice Test", contentW, 26);
  titleLines.forEach(line => { doc.text(line, margin, y); y += 34; });

  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  doc.setTextColor(...COLORS.muted);
  if (deckTitle) { doc.text(`Subject: ${deckTitle}`, margin, y); y += 18; }
  doc.text(`Date: ___________________`, margin, y); y += 18;
  doc.text(`Name: ___________________`, margin, y); y += 18;
  doc.text(`Score: _______ / ${questions.length}`, margin, y); y += 36;

  doc.setDrawColor(...COLORS.line);
  doc.setLineWidth(0.5);
  doc.line(margin, y, W - margin, y);
  y += 24;

  doc.setFontSize(10);
  doc.setTextColor(...COLORS.muted);
  doc.text(`${questions.length} questions  ·  Generated by Cognita`, margin, y);
  y += 40;

  // ─── Questions ──────────────────────────────────────────────────────────────
  const totalPages = includeAnswerKey ? "?" : "?"; // will patch after
  let pageNum = 1;

  questions.forEach((q, i) => {
    const typeLabel = (q.type || "").replace("_", " ").toUpperCase();
    let qText = q.type === "true_false" ? q.statement : q.type === "matching" ? "Match each term to its definition." : q.question;
    const qLines = wrapText(`${i + 1}. ${qText}`, contentW, 11);
    const estimatedHeight = 30 + qLines.length * 15 + 80; // rough
    ensureSpace(estimatedHeight);

    if (y === margin) { drawHeader("Practice Test"); }

    // Question number badge
    doc.setFillColor(...COLORS.primary);
    doc.roundedRect(margin, y - 11, 26, 16, 3, 3, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(255, 255, 255);
    doc.text(String(i + 1), margin + 13, y, { align: "center" });

    // Type label
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(...COLORS.muted);
    doc.text(typeLabel, margin + 32, y);

    y += 4;
    // Question text
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...COLORS.dark);
    qLines.forEach(line => { doc.text(line, margin + 32, y); y += 15; });
    y += 4;

    // ── Multiple Choice ──
    if (q.type === "multiple_choice" && q.options) {
      const letters = ["A", "B", "C", "D"];
      q.options.forEach((opt, j) => {
        const optLines = wrapText(`${letters[j]}.  ${opt}`, contentW - 20, 10);
        ensureSpace(optLines.length * 14 + 6);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(10);
        doc.setTextColor(...COLORS.dark);
        // Circle bubble
        doc.setDrawColor(...COLORS.muted);
        doc.setFillColor(...COLORS.bubble);
        doc.circle(margin + 8, y - 3, 5, "FD");
        optLines.forEach((line, li) => {
          doc.text(line, margin + 20, y);
          y += 14;
        });
      });
    }

    // ── True / False ──
    if (q.type === "true_false") {
      ensureSpace(30);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);
      doc.setTextColor(...COLORS.dark);
      doc.setDrawColor(...COLORS.muted);
      doc.setFillColor(...COLORS.bubble);
      doc.circle(margin + 8, y - 3, 5, "FD");
      doc.text("True", margin + 20, y);
      y += 16;
      doc.circle(margin + 8, y - 3, 5, "FD");
      doc.text("False", margin + 20, y);
      y += 16;
    }

    // ── Matching ──
    if (q.type === "matching" && q.pairs) {
      const leftItems = q.pairs.map(p => p.left);
      const rightItems = [...q.pairs.map(p => p.right)].sort(() => Math.random() - 0.5);
      ensureSpace(q.pairs.length * 18 + 30);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9);
      doc.setTextColor(...COLORS.dark);

      // Column headers
      doc.setFont("helvetica", "bold");
      doc.text("Terms", margin, y);
      doc.text("Definitions", W / 2 + 10, y);
      y += 14;
      doc.setFont("helvetica", "normal");

      leftItems.forEach((left, j) => {
        doc.text(`${j + 1}. ${left}`, margin, y);
        doc.text(`${String.fromCharCode(65 + j)}. ${rightItems[j]}`, W / 2 + 10, y);
        // Answer blank
        doc.text(`____`, margin + 180, y);
        y += 16;
      });
    }

    // ── Written ──
    if (q.type === "written") {
      ensureSpace(50);
      doc.setDrawColor(...COLORS.line);
      doc.setLineWidth(0.4);
      for (let l = 0; l < 3; l++) {
        y += 18;
        doc.line(margin, y, W - margin, y);
      }
      y += 6;
    }

    y += 14;
    // Divider
    doc.setDrawColor(...COLORS.line);
    doc.setLineWidth(0.3);
    doc.line(margin, y, W - margin, y);
    y += 16;
  });

  // ─── Answer Key (optional) ────────────────────────────────────────────────
  if (includeAnswerKey) {
    doc.addPage();
    drawHeader("Answer Key");
    y = 60;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(...COLORS.primary);
    doc.text("Answer Key", margin, y);
    y += 28;

    questions.forEach((q, i) => {
      ensureSpace(40);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(10);
      doc.setTextColor(...COLORS.dark);
      doc.text(`${i + 1}.`, margin, y);

      doc.setFont("helvetica", "normal");
      let answerText = "";
      if (q.type === "multiple_choice") {
        const letters = ["A", "B", "C", "D"];
        answerText = `${letters[q.correct] || ""}  —  ${q.options?.[q.correct] || ""}`;
      } else if (q.type === "true_false") {
        answerText = q.is_true ? "True" : "False";
      } else if (q.type === "written") {
        answerText = q.correct_answer || "";
      } else if (q.type === "matching") {
        answerText = (q.pairs || []).map((p, j) => `${j + 1}→${String.fromCharCode(65 + j)}`).join("  ");
      }
      const ansLines = wrapText(answerText, contentW - 30, 10);
      doc.setTextColor(...COLORS.dark);
      ansLines.forEach(line => { doc.text(line, margin + 22, y); y += 14; });
      y += 4;
    });

    y += 20;
    // Watermark bar
    doc.setFillColor(...COLORS.primary);
    doc.rect(margin, y, contentW, 26, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(255, 255, 255);
    doc.text("✦  Generated by Cognita — AI-Powered Study Platform  ✦", W / 2, y + 17, { align: "center" });
  }

  // ─── Watermark on last content page ─────────────────────────────────────
  if (!includeAnswerKey) {
    doc.setFillColor(...COLORS.primary);
    doc.rect(margin, H - 55, contentW, 26, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(255, 255, 255);
    doc.text("✦  Generated by Cognita — AI-Powered Study Platform  ✦", W / 2, H - 55 + 17, { align: "center" });
  }

  const safeName = (title || "test").replace(/[^a-z0-9]/gi, "_").toLowerCase();
  doc.save(`${safeName}.pdf`);
}